### ISSUE TITLE
Migrate Authentications

### ISSUE THREAD

**Issue by HonzaTuron** [apify/openapi#17]
- [ ] File structure -> based on path name, e.g /openapi/paths/actor-builds
- [ ] Fix operationId - make it camelCased - e.g GetListOfKeyValueStores
- [ ] File name of endpoints -> remove v2@ e.g. actor-tasks@{actorTaskId}@input.yaml

**Comment by drobnikj** [comment]
Done https://github.com/apify/openapi/pull/38
